# Auto-Generated by cargo-bitbake 0.3.16
#
inherit cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get test_dlt_rs could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/test_dlt_rs/0.1.0"
SRC_URI += "git://gitlab.com/vrion69/dlt-wrapper-test-rs.git;protocol=https;branch=main"
SRCREV = "1b5321289c8dca2478566548a60edc6c7741de13"
S = "${WORKDIR}/git"
CARGO_SRC_DIR = ""
PV:append = ".AUTOINC+1b5321289c"
BB_STRICT_CHECKSUM:forcevariable = "0"
# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
    crate://crates.io/aho-corasick/1.0.4 \
    crate://crates.io/bindgen/0.66.1 \
    crate://crates.io/bitflags/2.4.0 \
    crate://crates.io/cexpr/0.6.0 \
    crate://crates.io/cfg-if/1.0.0 \
    crate://crates.io/clang-sys/1.6.1 \
    crate://crates.io/either/1.9.0 \
    crate://crates.io/glob/0.3.1 \
    crate://crates.io/lazy_static/1.4.0 \
    crate://crates.io/lazycell/1.3.0 \
    crate://crates.io/libc/0.2.147 \
    crate://crates.io/libloading/0.7.4 \
    crate://crates.io/log/0.4.20 \
    crate://crates.io/memchr/2.5.0 \
    crate://crates.io/minimal-lexical/0.2.1 \
    crate://crates.io/nom/7.1.3 \
    crate://crates.io/once_cell/1.18.0 \
    crate://crates.io/peeking_take_while/0.1.2 \
    crate://crates.io/prettyplease/0.2.12 \
    crate://crates.io/proc-macro2/1.0.66 \
    crate://crates.io/quote/1.0.33 \
    crate://crates.io/regex-automata/0.3.6 \
    crate://crates.io/regex-syntax/0.7.4 \
    crate://crates.io/regex/1.9.3 \
    crate://crates.io/rustc-hash/1.1.0 \
    crate://crates.io/shlex/1.1.0 \
    crate://crates.io/syn/2.0.29 \
    crate://crates.io/unicode-ident/1.0.11 \
    crate://crates.io/which/4.4.0 \
    crate://crates.io/winapi-i686-pc-windows-gnu/0.4.0 \
    crate://crates.io/winapi-x86_64-pc-windows-gnu/0.4.0 \
    crate://crates.io/winapi/0.3.9 \
    git://gitlab.com/vrion69/dlt-wrapper-rs.git;protocol=https;nobranch=1;name=dlt_wrapper_rs;destsuffix=dlt_wrapper_rs;\
"
DEPENDS += " dlt-daemon"
export BINDGEN_EXTRA_CLANG_ARGS="-I${STAGING_INCDIR}"
SRCREV_FORMAT .= "_dlt_wrapper_rs"
SRCREV_dlt_wrapper_rs = "5b5ec57ae91cf62865bd696614571d55ca19e5d7"
EXTRA_OECARGO_PATHS += "${WORKDIR}/dlt_wrapper_rs"

# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM = " \
    file://LICENSE;md5=86d3f3a95c324c9479bd8986968f4327 \
"

SUMMARY = "Test for dlt wrapper"
HOMEPAGE = "https://gitlab.com/vrion69/dlt-wrapper-test-rs.git"
LICENSE = "Apache-2.0"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include test_dlt_rs-${PV}.inc
include test_dlt_rs.inc
